version: '3'
services:
  database:
    image: neo4j:3.5.1
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - ./neo4j/data:/data
  #app:

#  redis:
#    image: redis:alpine
#    ports:
#    - "6379:6379"